from datetime import datetime
from typing import Protocol


class DigestSubscriptionRepositoryProtocol(Protocol):
    async def subscribe(self, user_id: int) -> None: ...

    async def unsubscribe(self, user_id: int) -> None: ...

    async def is_subscribed(self, user_id: int) -> bool: ...

    async def list_due(self, threshold: datetime) -> list[int]: ...

    async def mark_sent(self, user_id: int, sent_at: datetime) -> None: ...


class ChannelRepositoryProtocol(Protocol):
    async def subscribe(self, user_id: int, handle: str) -> None: ...

    async def unsubscribe(self, user_id: int, handle: str) -> None: ...

    async def get_subscriptions(self, user_id: int) -> list[str]: ...

    async def is_subscribed(self, user_id: int, handle: str) -> bool: ...


class RepoRepositoryProtocol(Protocol):
    async def add_repo(self, user_id: int, repo: str) -> None: ...

    async def remove_repo(self, user_id: int, repo: str) -> None: ...

    async def get_repos(self, user_id: int) -> list[str]: ...

    async def has_repo(self, user_id: int, repo: str) -> bool: ...


class InterestsRepositoryProtocol(Protocol):
    async def add_interest(self, user_id: int, interest: str) -> None: ...

    async def remove_interest(self, user_id: int, interest: str) -> None: ...

    async def get_interests(self, user_id: int) -> list[str]: ...

    async def has_interest(self, user_id: int, interest: str) -> bool: ...


class SeenItemsRepositoryProtocol(Protocol):
    async def filter_unseen(self, user_id: int, ids: list[str]) -> list[str]: ...

    async def mark_many_seen(self, user_id: int, ids: list[str]) -> None: ...


class VideoRepositoryProtocol(Protocol):
    async def upsert_metadata(
            self,
            video_id: str,
            title: str | None = None,
            channel_id: str | None = None,
            channel_title: str | None = None,
            published_at: datetime | None = None,
    ) -> None: ...

    async def get_metadata(self, video_id: str) -> tuple[str, str] | None: ...

    async def get_transcript(self, video_id: str) -> tuple[str, str] | None: ...

    async def set_transcript(self, video_id: str, transcript: str, language: str) -> None: ...

    async def get_summary(self, video_id: str) -> str | None: ...

    async def set_summary(self, video_id: str, summary: str) -> None: ...

    async def set_summary_embedding(self, video_id: str, embedding: list[float]) -> None: ...
